--- #YAML:1.0
name:               Digest-GOST
version:            0.04
abstract:           Perl interface to the GOST R 34.11-94 digest algorithm
author:
    - gray <gray@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.82
requires:
    Digest:  0
    parent:  0
resources:
    repository:  http://github.com/gray/digest-gost
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
